# Generated by Django 6.0.2 on 2026-03-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0002_remove_post_image_post_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('STORY', 'Story'), ('TECH', 'Tech')], max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='syntaxandstories.post')),
            ],
        ),
    ]
