# Generated by Django 6.0.2 on 2026-03-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
