# Generated by Django 6.0.2 on 2026-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0002_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TECH', 'Tech'), ('STORY', 'Story'), ('LIFESTYLE', 'Lifestyle'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
