# Generated by Django 6.0.2 on 2026-03-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_tags',
            options={'verbose_name_plural': 'Post Tag'},
        ),
    ]
