# Generated by Django 6.0.2 on 2026-03-06 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0004_saveposts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavePosts',
            new_name='SavedPosts',
        ),
    ]
