# Generated by Django 6.0.2 on 2026-03-06 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0005_rename_saveposts_savedposts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedposts',
            options={'verbose_name_plural': 'Saved Posts'},
        ),
        migrations.AlterField(
            model_name='savedposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to='syntaxandstories.post'),
        ),
        migrations.AlterField(
            model_name='savedposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to=settings.AUTH_USER_MODEL),
        ),
    ]
