# Generated by Django 6.0.2 on 2026-03-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0006_alter_follow_following_alter_like_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
