# Generated by Django 6.0.2 on 2026-03-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0006_alter_savedposts_options_alter_savedposts_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saves_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
