# Generated by Django 6.0.2 on 2026-03-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0009_alter_comment_options_savedposts_unique_saved_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
