# Generated by Django 6.0.2 on 2026-03-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxandstories', '0011_alter_post_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISH', 'Publish')], default='PUBLISH'),
        ),
    ]
